### ISSUE TITLE
[6.3.1] Missing lib folder

### ISSUE THREAD

**Issue by devel-pa** [erikras/redux-form#2249]
Hi, published package not working

**Comment by PaulMest** [comment]
I have the same issue. When I try to build with 6.3.0, it works fine. But with redux-form 6.3.1, I get:
`Module not found: Error: Cannot resolve module 'redux-form'`

**Comment by bmcminn** [comment]
Verified `package.json` is listing the following `main` config which doesn't exist:

https://github.com/erikras/redux-form/blob/master/package.json#L5

```json
 5 |  "main": "./lib/index.js",
  ...
````

**Comment by cpeddecord** [comment]
same, from my CI pipeline:

```
Error: Cannot find module './lib/immutable'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/lib/jenkins/workspace/CICEXP/checkout/PRA/node_modules/redux-form/immutable.js:1:18)
```

**Comment by cpeddecord** [comment]
also, thanks for your awesome lib :)

**Comment by aerze** [comment]
+1

**Comment by hankyates** [comment]
+1

**Comment by mattlubner** [comment]
Any particular reason why the npm publish action happens outside of Travis? Had it been in Travis, the latest (broken) version wouldn't have been published.

**Comment by SimenB** [comment]
travis failed for the tag build though

https://travis-ci.org/erikras/redux-form/builds/182395135

**Comment by mattlubner** [comment]
Exactly, Travis doesn't run publish tasks if the build fails or errors.

**Comment by JustinJKlein** [comment]
I also ran into this issue as well. You can just manually place the lib file in most cases from a previous build or install of the node module into the reduxform node module. That is working for me now until they have the repo updated for us. 

Thanks for the great library guys it is very useful and saves me quite a bit of time!

**Comment by emadow** [comment]
+1

**Comment by chenbin1985** [comment]
+1

**Comment by erikras** [comment]
GAH! I started using `np` to bump versions and publish. Will fix ASAP.

**Comment by erikras** [comment]
The Travis thing was because yarn failed. https://github.com/yarnpkg/yarn/issues/2199

**Comment by erikras** [comment]
Fixed in [`v6.3.2`](https://github.com/erikras/redux-form/releases/tag/v6.3.2). Apologies!! 😳

**Comment by emadow** [comment]
Thank you @erikras!

**Comment by ericdfields** [comment]
Might be a different instance, but I get this when compiling examples/simple-form:

```
ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'redux-form' in /Users/EricFields/Development/redux-form/examples/simple/src
 @ ./src/index.js 15:17-38

ERROR in ./src/SimpleForm.js
Module not found: Error: Cannot resolve module 'redux-form' in /Users/EricFields/Development/redux-form/examples/simple/src
 @ ./src/SimpleForm.js 11:17-38
```
