### ISSUE TITLE
`webpack 3.3` will cause some error

### ISSUE THREAD

**Issue by geminiyellow** [erikras/redux-form#3269]
### What is the current behavior?

I use [How to reduce redux-form's bundle size?](http://redux-form.com/7.0.3/docs/faq/BundleSize.md/#how-to-reduce-code-redux-form-code-39-s-bundle-size-)  to reduce the size of redux-form. 

6.x work good, but when i update to 7.x, i modify anything in the project, have to restart the webpack watch process, or else, there is `Uncaught TypeError: (0 , _reduxForm2.default) is not a function`.

### What's your environment?

node: latest
npm: latest
webpack: latest
babel: latest
redux-form: latest

**Comment by erikras** [comment]
Hmm... your `node_modules/redux-form/es/reduxForm.js` _does_ have an `export default` in it, correct?

**Comment by geminiyellow** [comment]
@erikras thanks for your reply. that maybe a `webpack 3.3.x` bug.
rollback to `webpack 3.0.0` it work well.

**Comment by pbarbiero** [comment]
@geminiyellow Are you using webpack 3 moduleconcatenationplugin? Theres a bug in that that was resolved in 3.4.0 that broke default exports in many modules.

**Comment by geminiyellow** [comment]
@pbarbiero thank you, 
yes, i using moduleconcatenationplugin and i has been tried 3.4, same error.

**Comment by spencerbeggs** [comment]
I am having this issue as well. Last version that worked for me is 3.1.0.

**Comment by geminiyellow** [comment]
@spencerbeggs 

webpack@3.2.0 + redux-form@latest is worked for me.
wating webpack team fix the bug.

**Comment by spencerbeggs** [comment]
@geminiyellow Can you identify what the issue is? I thought it might be in the transform.

**Comment by geminiyellow** [comment]
here 

[webpack --watch breaking site after modifying a file #5399](https://github.com/webpack/webpack/issues/5399)

**Comment by gustavohenke** [comment]
Closing due to inactivity.
