### ISSUE TITLE
issues when upgrading from 5 to 6

### ISSUE THREAD

**Issue by szokrika** [erikras/redux-form#1636]
```
import { combineReducers } from 'redux';
// some other reducers
import validate from './validate_contact_form';
import { reducer as formReducer } from 'redux-form'

const rootReducer = combineReducers({
    // some other reducers
    form: formReducer.validation({ contactForm: validate })
});
export default rootReducer;
```
throws:

**Uncaught TypeError: _reduxForm.reducer.validation is not a function**

```
class Form extends Component {
//form fields..
}

export default reduxForm({
    form: 'contactForm'
})(Form);
```

**Comment by Sir4ur0n** [comment]
Did you check [Sync validation](http://redux-form.com/6.0.1/examples/syncValidation/) and [Async validation](http://redux-form.com/6.0.1/examples/asyncValidation/)?

Validation declaration happens in the form, not in the reduction declaration:
```javascript
export default reduxForm({
  form: 'asyncValidation', // a unique identifier for this form
  validate, // synchronous validation function
  asyncValidate, // asynchronous validation function
  asyncBlurFields: [ 'username' ]
})(AsyncValidationForm)
```

**Comment by szokrika** [comment]
@Sir4ur0n http://redux-form.com/6.0.1/docs/MigrationGuide.md/ is the migration guide not accurate?

**Comment by Sir4ur0n** [comment]
@erikras There's something weird. [Async validation doc](http://redux-form.com/6.0.1/examples/asyncValidation/) mentions the syntax I wrote above, while I found [the Async validation reducer.js file](https://github.com/erikras/redux-form/blob/master/examples/asyncValidation/src/reducer.js) contains the syntax @szokrika mentions in the first post (`formReducer.validation` in the `combineReducers`).

Any idea why?

**Comment by aaristotle75** [comment]
I have the same issue as @szokrika. I'm following the v5-v6 migration guide: [http://redux-form.com/6.0.0-alpha.4/docs/MigrationGuide.md/](url)

**Uncaught TypeError: _reduxForm.reducer.validation is not a function**

**Comment by deoqc** [comment]
I believe the sync validation was done in the reducer in [6.0.0-alpha](http://redux-form.com/6.0.0-alpha.4/examples/syncValidation/) but [moved back to reduxForm](http://redux-form.com/6.0.1/examples/syncValidation/) (as were done in v5).

**Comment by szokrika** [comment]
OK, that is there anything else outdated in the migration guide?

**Comment by deoqc** [comment]
Well, the [migration guide](http://redux-form.com/6.0.1/docs/MigrationGuide.md/) seems updated in this part:
> Sync validation is exactly the same as in v5.

Maybe you are referring to an older version (some v6 alpha)?

**Comment by erikras** [comment]
> `form: formReducer.validation({ contactForm: validate })`

Yes, this is from a _very_ old alpha version.

If there is another problem here, I'm not understanding what it is.

**Comment by szokrika** [comment]
Sounds good, now my only problem is: how to update a redux form field from another 3rd party React component (Google Places autocomplete for example), can you help?

**Comment by szokrika** [comment]
Thanks guys, my issues are resolved. 
If anyone interested:
http://stackoverflow.com/questions/39173098/update-redux-form-field-from-a-callback
