### ISSUE TITLE
Immutable FieldArrays broken with Immutable 4.0.0-rc.5+

### ISSUE THREAD

**Issue by ssilve1989** [erikras/redux-form#3489]
### Are you submitting a **bug report** or a **feature request**?

Bug

### What is the current behavior?

Using FieldArrays results in `Uncaught TypeError: original.mergeDeepWith is not a function`

### What is the expected behavior?

Expected to not do that.

### What's your environment?

redux-form@7.0.4
immutable@4.0.0-rc.7
node@7.10.1

### Other information

The method `mergeDeepWith` has been removed from the List API since 4.0.0-rc.5 so now any interaction with FieldArrays causes this exception to show up.

**Comment by erikras** [comment]
Try [`v7.1.0`](https://github.com/erikras/redux-form/releases/tag/v7.1.0)? That's the first version with `immutable@4.0.0-rc.5` used in the tests.

**Comment by joeflynn** [comment]
I'm also experiencing this issue when calling `input.onChange(numberValue)`. 

I'm running redux-form@7.1.0 & immutable@4.0.0-rc.7.

**Comment by ssilve1989** [comment]
@erikras I still see the error `TypeError: original.mergeDeepWith is not a function` using FieldArrays with `redux-form@v7.1.0`

**Comment by thessem** [comment]
`mergeDeepWith` was removed here https://github.com/facebook/immutable-js/pull/1344

**Comment by TikiTDO** [comment]
I tried replicating the old mergeDeep behavior here: https://github.com/TikiTDO/redux-form/commit/fd7d616efa8149a26314d74bd4c0236598cd3434

It seems to work well enough for my use case, but I'm not entirely sure what problem is being solved here, so I can't speak to other scenarios.

**Comment by TikiTDO** [comment]
@erikras If you get a second could you comment on the above fix? This issue is hitting us pretty hard.

**Comment by bogdaniy** [comment]
All my form with FieldArrays is broken after updating immutable-js version to 4.0.0-rc.7, my redux-form version is 7.2.0

**Comment by Defenderbass** [comment]
Any news? We are very much looking forward to solving the problem

**Comment by gustavohenke** [comment]
No news, sorry.

**Comment by Defenderbass** [comment]
@gustavohenke do you plan to solve this issue?

**Comment by TikiTDO** [comment]
@Defenderbass I'm still waiting for someone to comment on my PR, but we've been using it for our project for a couple of weeks now with no issues.

**Comment by Defenderbass** [comment]
@TikiTDO I tried to use your option, but the fields began to disappear from the array. That is, the merge was not done correctly. I had to come up with my own version

**Comment by TikiTDO** [comment]
@Defenderbass I tried to reproduce what the functionality of the original mergeDeepWith, but didn't spend too much time on it. I can go fix mine, but if you believe yours works then I'm good with that too. If you have a branch I can try let me know and I'll see if it solves my problem too.

**Comment by Defenderbass** [comment]
@TikiTDO Look here #3692 . There everything is corny, but it works

**Comment by TikiTDO** [comment]
@Defenderbass Sounds good. I'm in an all day meeting, but I'll give it a try this evening.

**Comment by erikras** [comment]
Published fix in [`v7.2.1`](https://github.com/erikras/redux-form/releases/tag/v7.2.1).
