### ISSUE TITLE
Normalisation is broken in 8.2.0

### ISSUE THREAD

**Issue by Asday** [erikras/redux-form#4465]
### Are you submitting a **bug report** or a **feature request**?

Bug report.

### What is the current behavior?

Providing any normalisation to a field causes an uncaught error `Device: (11:8840) this.ref.current.getValue is not a function. (In 'this.ref.current.getValue()', 'this.ref.current.getValue' is undefined)` and no normalisation happens.  Note that the error only shows in react native - in the browser there appears to be no error, but entering a value is impossible.

### What is the expected behavior?
No error, and normalisation should happen.

### Sandbox Link

https://codesandbox.io/s/reduxform-template-43qmv
https://snack.expo.io/BJG4YvH6V

### What's your environment?

```
    "lodash": "4.17.11",
    "react": "16.5.0",
    "react-dom": "16.5.0",
    "react-redux": "5.0.7",
    "redux": "4.0.1",
    "redux-form": "8.2.0"
```

### Other information

Works fine on 7.4.2.  _Probably_ related to #4456 #4457 #4454 and #4439?

**Comment by renatoagds** [comment]
Hi @Asday , can you confirm if [`v8.2.1`](https://github.com/erikras/redux-form/releases/tag/v8.2.1) fix this problem? If yes, can you close the issue?

**Comment by Asday** [comment]
It unfortunately doesn't - updated the title and deps to match.

**Comment by westn** [comment]
Seems to be functional with the latest version of each package?
https://codesandbox.io/s/redux-form-template-mk1ti

**Comment by SerWonka** [comment]
the react-redux case since version 7 normalize doesn't work

**Comment by mikesir87** [comment]
Confirming that this is still a problem with 8.2.6 as well.

**Comment by big-toni** [comment]
When is this going to be fixed?
Using format callback is not a good alternative...

**Comment by Rafael-Ramblas** [comment]
I updated the react-redux to the latest, solved for me

**Comment by mikesir87** [comment]
So it's working for you with 8.2.6 @Rafael-Ramblas? I was still getting errors with it myself.

**Comment by Rafael-Ramblas** [comment]
If you upgrade the sandbox example to the latest of each lib, it starts to work
https://codesandbox.io/s/redux-form-template-jj97p

**Comment by westn** [comment]
I've upgraded every package, mainly `react-redux`, `redux` and `redux-form` and it's now working for me with normalization on `8.2.6`

**Comment by TomFletcher0** [comment]
Original post from @Asday says he's using react-redux 5.0.7, but react-redux has a peer-dependency on react-redux 6 or above (see https://github.com/redux-form/redux-form/blob/master/package.json#L110)
Upgrade to react-redux 6 or above and the problem should go away (it did for me).
